# Generated by Django 3.1.7 on 2021-03-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happyc', models.IntegerField()),
                ('Solutions', models.IntegerField()),
                ('hos', models.IntegerField()),
                ('team', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField(max_length=200)),
                ('DOB', models.DateField()),
                ('pincode', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='pics')),
                ('resume', models.FileField(upload_to='resume')),
            ],
        ),
    ]
