# Generated by Django 3.1.7 on 2021-03-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resume',
        ),
    ]
