# Generated by Django 3.1.7 on 2021-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_auto_20210331_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
