# Generated by Django 3.1.7 on 2021-03-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0004_auto_20210331_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='resume',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
    ]
