# Generated by Django 3.1.7 on 2021-03-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0005_auto_20210331_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.TextField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
