# Generated by Django 3.1.7 on 2021-04-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0006_auto_20210331_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Lastname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
