# Generated by Django 3.1.7 on 2021-04-13 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0008_follow_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 7, 1, 55, 28657, tzinfo=utc)),
        ),
    ]
