# Generated by Django 3.1.7 on 2021-04-14 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0009_auto_20210413_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 4, 14, 8, 37, 49, 235958, tzinfo=utc))),
                ('to_id', models.IntegerField()),
                ('fro_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='follow_model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 8, 37, 49, 235958, tzinfo=utc)),
        ),
    ]
