# Generated by Django 3.1.7 on 2021-04-14 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0010_auto_20210414_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_model',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='friends',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
