# Generated by Django 3.1.7 on 2021-04-15 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0011_auto_20210414_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejected', models.DateTimeField()),
                ('viewd', models.DateTimeField()),
                ('to_id', models.IntegerField()),
                ('fro_id', models.IntegerField()),
            ],
        ),
    ]
