# Generated by Django 3.1.7 on 2021-04-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0012_request_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_model',
            name='rejected',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='request_model',
            name='viewd',
            field=models.DateTimeField(default=0),
        ),
    ]
