# Generated by Django 3.1.7 on 2021-04-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0013_auto_20210415_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_model',
            name='rejected',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='request_model',
            name='viewd',
            field=models.DateTimeField(blank=True),
        ),
    ]
