# Generated by Django 3.1.7 on 2021-04-15 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0014_auto_20210416_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_model',
            name='rejected',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request_model',
            name='viewd',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
