# Generated by Django 3.1.7 on 2021-04-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0017_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Replies', models.IntegerField(null=0)),
                ('retweet', models.IntegerField(null=0)),
                ('Likes', models.IntegerField(null=0)),
                ('rep', models.TextField()),
                ('comm', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
