# Generated by Django 3.1.7 on 2021-04-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0018_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='posts',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='use',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
