# Generated by Django 3.1.7 on 2021-04-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0019_auto_20210428_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Replies',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='comm',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='rep',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='retweet',
            field=models.IntegerField(null=True),
        ),
    ]
