# Generated by Django 3.1.7 on 2021-04-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0020_auto_20210428_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='usname',
            field=models.TextField(null=True),
        ),
    ]
