# Generated by Django 3.1.7 on 2021-04-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0021_auto_20210429_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
