# Generated by Django 3.1.7 on 2021-05-01 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0022_auto_20210429_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='pslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Replies', models.IntegerField(null=True)),
                ('retweet', models.IntegerField(null=True)),
                ('Likes', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='Likes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='Replies',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='retweet',
        ),
        migrations.AddField(
            model_name='posts',
            name='plis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ap.pslist'),
        ),
    ]
