# Generated by Django 3.1.7 on 2021-05-01 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0023_auto_20210501_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='lks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Likes', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Replies', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='retw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweet', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='plis',
        ),
        migrations.DeleteModel(
            name='pslist',
        ),
        migrations.AddField(
            model_name='retw',
            name='plis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ap.posts'),
        ),
        migrations.AddField(
            model_name='reps',
            name='plis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ap.posts'),
        ),
        migrations.AddField(
            model_name='lks',
            name='plis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ap.posts'),
        ),
    ]
