# Generated by Django 3.1.7 on 2021-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0024_auto_20210501_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Like',
            field=models.IntegerField(null=True),
        ),
    ]
