# Generated by Django 3.1.7 on 2021-05-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0025_posts_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='retweet',
            field=models.IntegerField(null=True),
        ),
    ]
