# Generated by Django 3.1.7 on 2021-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmsg',
            name='fro_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmsg',
            name='to_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
